/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz1;

import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class VentanaAdd extends javax.swing.JFrame {
    
    String numero;
    Playlist lista;
    /**
     * Creates new form VentanaAdd
     * @param numero
     */
    public VentanaAdd(String numero,Playlist lista) {
        this.numero=numero;
        this.lista = lista;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumeroDeCancion = new javax.swing.JLabel();
        JLableNombre = new javax.swing.JLabel();
        JLabelArtista = new javax.swing.JLabel();
        JLabelReproducciones = new javax.swing.JLabel();
        JLabelAno = new javax.swing.JLabel();
        JLabelIdioma = new javax.swing.JLabel();
        boxArtista = new javax.swing.JTextField();
        boxReproducciones = new javax.swing.JTextField();
        boxNombre = new javax.swing.JTextField();
        boxAno = new javax.swing.JTextField();
        boxIdioma = new javax.swing.JTextField();
        JLabelNUmeroDeCancion2 = new javax.swing.JLabel();
        anadirAlPlaylist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNumeroDeCancion.setText("Numero de cancion");
        getContentPane().add(jLabelNumeroDeCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 58, 123, -1));

        JLableNombre.setText("Nombre de la canción");
        getContentPane().add(JLableNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 104, -1, -1));

        JLabelArtista.setText("Artista");
        getContentPane().add(JLabelArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 146, 123, -1));

        JLabelReproducciones.setText("Número de reproducciones");
        getContentPane().add(JLabelReproducciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 188, -1, -1));

        JLabelAno.setText("Año");
        getContentPane().add(JLabelAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 230, 155, -1));

        JLabelIdioma.setText("Idioma");
        getContentPane().add(JLabelIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 264, 155, -1));
        getContentPane().add(boxArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 138, 397, -1));
        getContentPane().add(boxReproducciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 397, -1));
        getContentPane().add(boxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 96, 397, -1));
        getContentPane().add(boxAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 397, -1));
        getContentPane().add(boxIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 397, -1));
        getContentPane().add(JLabelNUmeroDeCancion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        anadirAlPlaylist.setText("Añadir");
        anadirAlPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirAlPlaylistActionPerformed(evt);
            }
        });
        getContentPane().add(anadirAlPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadirAlPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirAlPlaylistActionPerformed
        if ((!boxNombre.getText().isBlank())&&(!boxArtista.getText().isBlank())&&(!boxReproducciones.getText().isBlank())&&(!boxAno.getText().isBlank())&&(!boxIdioma.getText().isBlank())){
            Cancion rolita = new Cancion(Integer.parseInt(numero),boxNombre.getText(),boxArtista.getText(),Integer.parseInt(boxReproducciones.getText()),Integer.parseInt(boxAno.getText()),boxIdioma.getText());
            Nodo nodito = new Nodo(rolita);
            this.lista.addToQueue(nodito);
            this.setVisible(false);
            MenuPrincipal window = new MenuPrincipal(lista);
            Funciones f = new Funciones();
            f.escribir_txt(lista);
            window.setVisible(true);
        }else {
            JOptionPane.showMessageDialog(null, "Asegurate que todos los campos hayan sido llenados");
        }
        
    }//GEN-LAST:event_anadirAlPlaylistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new VentanaAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelAno;
    private javax.swing.JLabel JLabelArtista;
    private javax.swing.JLabel JLabelIdioma;
    public javax.swing.JLabel JLabelNUmeroDeCancion2;
    private javax.swing.JLabel JLabelReproducciones;
    private javax.swing.JLabel JLableNombre;
    private javax.swing.JButton anadirAlPlaylist;
    private javax.swing.JTextField boxAno;
    private javax.swing.JTextField boxArtista;
    private javax.swing.JTextField boxIdioma;
    private javax.swing.JTextField boxNombre;
    private javax.swing.JTextField boxReproducciones;
    private javax.swing.JLabel jLabelNumeroDeCancion;
    // End of variables declaration//GEN-END:variables
}
