/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplication;

import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();
        textAreaBox.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearButton = new javax.swing.JButton();
        mezclarButton = new javax.swing.JButton();
        printMezclaButton = new javax.swing.JButton();
        printRechazadosButton = new javax.swing.JButton();
        tamanoBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearButton.setText("Crear Arbol");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(crearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        mezclarButton.setText("Mezclar Bosque");
        mezclarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mezclarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mezclarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        printMezclaButton.setText("Imprimir Mezcla");
        printMezclaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printMezclaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(printMezclaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        printRechazadosButton.setText("Imprimir Valores Rechazados");
        printRechazadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printRechazadosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(printRechazadosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));
        getContentPane().add(tamanoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 73, 72, -1));

        jLabel1.setText("Tamaño:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        textAreaBox.setColumns(20);
        textAreaBox.setRows(5);
        jScrollPane1.setViewportView(textAreaBox);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        String tamano = tamanoBox.getText();
        Funciones f = new Funciones();
        try{
            int tamanoI = Integer.parseInt(tamano);
            if (tamanoI > 0 && tamanoI < 10){
            f.agregarArbol(tamanoI);
            }else{
                JOptionPane.showMessageDialog(null, "Ocurrio un error: Ingrese valores menores de 1000 y positivos"  );
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ocurrio un error: \n" + e);
        }
    }//GEN-LAST:event_crearButtonActionPerformed

    private void mezclarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mezclarButtonActionPerformed
        
        Global.mezclarBosque();
    }//GEN-LAST:event_mezclarButtonActionPerformed

    private void printMezclaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printMezclaButtonActionPerformed
        String texto = "";
        textAreaBox.setText(texto);
        if (Global.mezcla.esVacio()){
            JOptionPane.showMessageDialog(null,"No hay mezcla.");
        }else{
            texto = Global.mezcla.preorden();
        }
        textAreaBox.setText(texto);
        
    }//GEN-LAST:event_printMezclaButtonActionPerformed

    private void printRechazadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printRechazadosButtonActionPerformed
        Funciones f = new Funciones();
        String texto = "";
        textAreaBox.setText(texto);
        if (Global.valoresRechazados.esVacio()){
            JOptionPane.showMessageDialog(null, "Todavia no ha habido ningun valor rechazado.");
        }else{
            texto = f.leerRechazados();
        }
        textAreaBox.setText(texto);
               
    }//GEN-LAST:event_printRechazadosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Global.inicializar();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mezclarButton;
    private javax.swing.JButton printMezclaButton;
    private javax.swing.JButton printRechazadosButton;
    private javax.swing.JTextField tamanoBox;
    private javax.swing.JTextArea textAreaBox;
    // End of variables declaration//GEN-END:variables
}
