/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Andres
 */
public class Ventana1 extends javax.swing.JPanel {
    
    public static String name2;

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterVentana1 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        exit = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterVentana1.setText("Enter");
        enterVentana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterVentana1ActionPerformed(evt);
            }
        });
        add(enterVentana1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        name.setText("Nombre");
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        nameInput.setText("Ingresa tu nombre");
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });
        add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 180, 30));

        exit.setText("X");
        add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void enterVentana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterVentana1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterVentana1ActionPerformed

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
        this.name2 = nameInput.getText();
    }//GEN-LAST:event_nameInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterVentana1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameInput;
    // End of variables declaration//GEN-END:variables
}
